import { Worker } from 'bullmq'
import { connection } from '../queues/connection'
import { type AiTriageJobData } from '../queues/ai-triage.queue'
import { db as supabase } from '../lib/db'
import { logger } from '../lib/logger'
import { invalidateMatchCaches } from '../lib/redis-cache'
import { CNAE_GROUPS, getCompanyDivisions } from '@licitagram/shared'
import { callLLM } from '../ai/llm-client'
import OpenAI from 'openai'
import { createHash } from 'crypto'
import IORedis from 'ioredis'

// ─── Triage Cache (Redis) ───────────────────────────────────────────────────

let triageCacheRedis: IORedis | null = null

function getTriageCache(): IORedis {
  if (!triageCacheRedis) {
    triageCacheRedis = new IORedis(process.env.REDIS_URL || 'redis://localhost:6379', {
      maxRetriesPerRequest: 3,
      lazyConnect: true,
    })
    triageCacheRedis.on('error', (err) => {
      logger.error({ err: err.message }, 'Triage cache Redis connection error')
    })
  }
  return triageCacheRedis
}

const TRIAGE_CACHE_PREFIX = 'triage:cache:'
const TRIAGE_CACHE_TTL = 24 * 60 * 60 // 24 hours

function triageCacheKey(companyId: string, objeto: string): string {
  const hash = createHash('md5').update(companyId + objeto.slice(0, 200)).digest('hex')
  return `${TRIAGE_CACHE_PREFIX}${hash}`
}

interface CachedTriageResult {
  score: number
  recomendacao: string
}

async function getTriageCached(key: string): Promise<CachedTriageResult | null> {
  try {
    const val = await getTriageCache().get(key)
    if (val) return JSON.parse(val) as CachedTriageResult
  } catch {
    // Redis down — skip cache
  }
  return null
}

async function setTriageCachedBatch(entries: Array<{ key: string; result: CachedTriageResult }>): Promise<void> {
  if (entries.length === 0) return
  try {
    const pipeline = getTriageCache().pipeline()
    for (const { key, result } of entries) {
      pipeline.set(key, JSON.stringify(result), 'EX', TRIAGE_CACHE_TTL)
    }
    await pipeline.exec()
  } catch {
    // Ignore
  }
}

const deepseekClient = new OpenAI({
  apiKey: process.env.DEEPSEEK_API_KEY || '',
  baseURL: 'https://api.deepseek.com',
})

// ─── Company Context Builder ─────────────────────────────────────────────────

function buildCompanyContext(company: Record<string, unknown>): string {
  const parts: string[] = []

  if (company.razao_social) parts.push(`Empresa: ${company.razao_social}`)
  if (company.nome_fantasia) parts.push(`Nome fantasia: ${company.nome_fantasia}`)

  const allCnaes: string[] = []
  if (company.cnae_principal) allCnaes.push(String(company.cnae_principal))
  if (Array.isArray(company.cnaes_secundarios)) allCnaes.push(...(company.cnaes_secundarios as string[]))

  const cnaeDescriptions: string[] = []
  for (const cnae of allCnaes) {
    const group = cnae.substring(0, 2)
    if (CNAE_GROUPS[group]) {
      cnaeDescriptions.push(`${cnae}: ${CNAE_GROUPS[group]}`)
    }
  }
  if (cnaeDescriptions.length > 0) {
    parts.push(`CNAEs e atividades:\n${cnaeDescriptions.join('\n')}`)
  }

  if (company.descricao_servicos) parts.push(`Servicos: ${String(company.descricao_servicos).slice(0, 1000)}`)
  if (Array.isArray(company.palavras_chave) && (company.palavras_chave as string[]).length > 0) {
    parts.push(`Palavras-chave: ${(company.palavras_chave as string[]).join(', ')}`)
  }
  if (Array.isArray(company.capacidades) && (company.capacidades as string[]).length > 0) {
    parts.push(`Capacidades: ${(company.capacidades as string[]).join(', ')}`)
  }

  return parts.join('\n')
}

// ─── Auto-generate company description from CNAEs ───────────────────────────

async function autoGenerateDescription(company: Record<string, unknown>): Promise<string | null> {
  const allCnaes: string[] = []
  if (company.cnae_principal) allCnaes.push(String(company.cnae_principal))
  if (Array.isArray(company.cnaes_secundarios)) allCnaes.push(...(company.cnaes_secundarios as string[]))

  if (allCnaes.length === 0) return null

  const cnaeDescriptions: string[] = []
  for (const cnae of allCnaes) {
    const group = cnae.substring(0, 2)
    if (CNAE_GROUPS[group]) {
      cnaeDescriptions.push(`${cnae}: ${CNAE_GROUPS[group]}`)
    }
  }

  const prompt = `Com base nos CNAEs abaixo, gere uma descricao concisa (3-5 frases) dos servicos que esta empresa oferece. Seja especifico sobre o que a empresa FAZ, nao apenas os codigos.

Empresa: ${company.razao_social || 'N/A'}
CNAEs:
${cnaeDescriptions.join('\n')}
${Array.isArray(company.palavras_chave) && (company.palavras_chave as string[]).length > 0 ? `Palavras-chave: ${(company.palavras_chave as string[]).join(', ')}` : ''}

Retorne APENAS a descricao, sem formatacao, sem markdown.`

  try {
    // Uses LLM cascade (Groq → OpenRouter models) — falls back automatically
    // if any provider is out of credits, rate limited, or down.
    const desc = (await callLLM({
      task: 'summary',
      system: 'Voce gera descricoes concisas de empresas baseado em CNAEs.',
      prompt,
    })).trim()

    if (desc && desc.length > 20) {
      await supabase
        .from('companies')
        .update({ descricao_servicos: desc })
        .eq('id', company.id as string)

      logger.info({ companyId: company.id, descLength: desc.length }, 'Auto-generated company description')
      return desc
    }
  } catch (err) {
    logger.warn({ companyId: company.id, err }, 'Failed to auto-generate description')
  }
  return null
}

// ─── AI Triage Prompt ────────────────────────────────────────────────────────

const TRIAGE_SYSTEM_PROMPT = `Voce e um classificador ULTRA-RIGOROSO de licitacoes. Recebe o perfil de uma empresa e uma lista de objetos de licitacoes. Para CADA licitacao, avalie se o objeto e DIRETAMENTE compativel com as atividades REAIS da empresa.

PRINCIPIO: O usuario PERDE TEMPO e DINHEIRO quando recebe licitacoes irrelevantes. Cada falso positivo custa horas de analise. Seja EXTREMAMENTE conservador.

REGRAS DE PONTUACAO:
- 0-15: INCOMPATIVEL — objeto nao tem relacao com os CNAEs/atividades da empresa
- 16-35: MUITO BAIXA — ramos diferentes, intersecao minima ou tangencial
- 36-50: BAIXA — alguma relacao mas NAO e atividade que a empresa realmente executa
- 51-65: MODERADA — empresa PODERIA participar mas nao e seu foco direto
- 66-80: BOA — objeto CLARAMENTE alinhado com CNAEs e servicos DECLARADOS da empresa
- 81-100: EXCELENTE — match DIRETO, exatamente o que a empresa faz no dia-a-dia

FILTROS OBRIGATORIOS (score 0-15 automatico):
- O objeto da licitacao e COMPLETAMENTE fora do setor/atividade da empresa (ex: empresa de saude e licitacao de combustivel; empresa de TI e licitacao de uniformes)
- A empresa NAO tem nenhum CNAE (principal ou secundario) que cubra a atividade

SCORE 66-80 (BOA) quando:
- O CNAE principal OU secundarios da empresa cobrem a atividade
- A descricao de servicos da empresa TEM relacao com o objeto
- A empresa poderia participar com suas competencias declaradas
- IMPORTANTE: aplique este criterio IGUALMENTE para TODOS os setores (saude, TI, construcao, etc.)

SCORE 81-100 (EXCELENTE) quando:
- Match DIRETO com o CNAE principal
- O objeto e EXATAMENTE o que a empresa faz no dia-a-dia
- Alta probabilidade de execucao bem-sucedida

IMPORTANTE - NEUTRALIDADE ENTRE SETORES:
- Avalie TODOS os setores com os MESMOS criterios. Uma empresa de saude que faz "prestacao de servicos medicos" deve receber score tao alto quanto uma empresa de TI que faz "desenvolvimento de software" quando o match e direto
- NAO penalize setores nao-tecnologicos. Saude, construcao, alimentacao, transporte sao tao validos quanto TI
- O que importa e: o CNAE cobre? A descricao de servicos menciona? A empresa PODE executar?

NAO de score alto para:
- Objetos genericos que "qualquer empresa" poderia fazer
- Objetos onde a empresa precisaria de capacidade que NAO possui
- Licitacoes que mencionam o setor da empresa apenas como componente MENOR

REGRAS ABSOLUTAS (nunca viole):
- Se NENHUM CNAE da empresa cobre o objeto da licitacao → score MAXIMO 30
- Se apenas CNAEs SECUNDARIOS cobrem parcialmente → score MAXIMO 60
- CNAE principal da empresa DEVE estar diretamente relacionado ao objeto para score > 70
- Empresa de engenharia civil (CNAE 41-43, 71) NAO pode ter score > 30 em licitacao de software/TI (CNAE 62, 63)
- Empresa de TI (CNAE 62, 63) NAO pode ter score > 30 em licitacao de construcao civil (CNAE 41-43)
- Termos genericos como "gestao", "projeto", "sistema" NAO indicam compatibilidade se os CNAEs sao de setores diferentes

Responda APENAS com JSON valido, sem texto adicional, sem markdown`

// ─── Triage a Single Batch ───────────────────────────────────────────────────

interface TriageResult {
  matchId: string
  score: number
  recomendacao: string
}

const LOW_SCORE_THRESHOLD = 20 // Matches below this are hidden (fora do escopo)

async function triageBatch(
  matchIds: string[],
  companyContext: string,
  companyId: string,
  companyCnaes: string[],
): Promise<TriageResult[]> {
  // Fetch matches with tender objects, skipping expired tenders
  const today = new Date().toISOString().split('T')[0]
  const { data: matches } = await supabase
    .from('matches')
    .select('id, company_id, tender_id, score, match_source, tenders!inner(id, objeto, valor_estimado, orgao_nome, uf, data_encerramento, cnae_classificados)')
    .in('id', matchIds)
    .or(`data_encerramento.is.null,data_encerramento.gte.${today}`, { referencedTable: 'tenders' })

  const skippedCount = matchIds.length - (matches?.length || 0)
  if (skippedCount > 0) {
    logger.info({ companyId, skipped: skippedCount }, 'Skipped expired tender matches')
  }

  if (!matches || matches.length === 0) return []

  // Build items
  const items = matches
    .filter((m: any) => m.tenders)
    .map((m: any) => {
      const t = m.tenders as unknown as Record<string, unknown>
      return {
        matchId: m.id as string,
        tenderId: t.id as string,
        objeto: ((t.objeto as string) || '').slice(0, 200),
        valorEstimado: t.valor_estimado as number | null,
        orgao: ((t.orgao_nome as string) || '').slice(0, 80),
        uf: t.uf as string,
        originalScore: m.score as number,
        matchSource: m.match_source as string,
        tenderCnaes: (t.cnae_classificados as string[]) || [],
      }
    })

  if (items.length === 0) return []

  // ─── Optimization 1: CNAE Pre-filter BEFORE AI call ──────────────────────
  // Same logic as the post-AI CNAE validation gate (lines below), but done
  // BEFORE wasting an API call. Items with ZERO CNAE overlap get score 10
  // and skip AI entirely. Items WITH overlap continue to AI as normal.

  const companyDivs = getCompanyDivisions(companyCnaes)
  const itemsForAI: typeof items = []
  const itemsSkipped: typeof items = []

  for (const item of items) {
    const tenderDivisions = item.tenderCnaes.map((c: string) => c.substring(0, 2))
    const hasDirectOverlap = tenderDivisions.some((d: string) => companyDivs.direct.has(d))
    const hasRelatedOverlap = tenderDivisions.some((d: string) => companyDivs.related.has(d))

    if (tenderDivisions.length > 0 && !hasDirectOverlap && !hasRelatedOverlap) {
      // ZERO CNAE overlap — skip AI, auto-score 10
      itemsSkipped.push(item)
    } else {
      itemsForAI.push(item)
    }
  }

  // ─── Process skipped items (no AI needed) ─────────────────────────────────
  const results: TriageResult[] = []
  const now = new Date().toISOString()
  const dbUpdates: PromiseLike<unknown>[] = []

  for (const item of itemsSkipped) {
    const updatePayload: Record<string, unknown> = {
      score: 10,
      match_source: 'ai_triage',
      recomendacao: 'nao_recomendado',
      analyzed_at: now,
    }

    if (item.matchSource !== 'ai' && item.matchSource !== 'ai_triage') {
      updatePayload.keyword_score = item.originalScore
    }

    dbUpdates.push(
      supabase
        .from('matches')
        .update(updatePayload)
        .eq('id', item.matchId),
    )

    results.push({
      matchId: item.matchId,
      score: 10,
      recomendacao: 'nao_recomendado',
    })
  }

  // ─── Optimization 2: Cache lookup BEFORE AI call ──────────────────────────
  const itemsToCallAI: typeof items = []
  const cacheKeys = new Map<string, string>() // matchId -> cacheKey
  let cacheHitCount = 0

  for (const item of itemsForAI) {
    const cKey = triageCacheKey(companyId, item.objeto)
    cacheKeys.set(item.matchId, cKey)

    const cached = await getTriageCached(cKey)
    if (cached) {
      cacheHitCount++
      let safeScore = Math.min(100, Math.max(0, Math.round(cached.score)))

      // Apply post-AI CNAE validation gate on cached results too
      const tenderDivisions = item.tenderCnaes.map((c: string) => c.substring(0, 2))
      const hasDirectOverlap = tenderDivisions.some((d: string) => companyDivs.direct.has(d))
      const hasRelatedOverlap = tenderDivisions.some((d: string) => companyDivs.related.has(d))

      if (tenderDivisions.length > 0 && !hasDirectOverlap && !hasRelatedOverlap) {
        safeScore = Math.min(safeScore, 35)
      } else if (tenderDivisions.length > 0 && !hasDirectOverlap && hasRelatedOverlap) {
        safeScore = Math.min(safeScore, 65)
      }

      const updatePayload: Record<string, unknown> = {
        score: safeScore,
        match_source: 'ai_triage',
        recomendacao: cached.recomendacao || null,
        analyzed_at: now,
      }

      if (item.matchSource !== 'ai' && item.matchSource !== 'ai_triage') {
        updatePayload.keyword_score = item.originalScore
      }

      dbUpdates.push(
        supabase
          .from('matches')
          .update(updatePayload)
          .eq('id', item.matchId),
      )

      results.push({
        matchId: item.matchId,
        score: safeScore,
        recomendacao: cached.recomendacao || 'avaliar_melhor',
      })
    } else {
      itemsToCallAI.push(item)
    }
  }

  // ─── Optimization 3: Log savings ──────────────────────────────────────────
  const estimatedTokensSaved = (itemsSkipped.length + cacheHitCount) * 600 // ~600 tokens per item avg
  logger.info(
    {
      companyId,
      totalItems: items.length,
      preFilteredSkipped: itemsSkipped.length,
      cacheHits: cacheHitCount,
      sentToAI: itemsToCallAI.length,
      estimatedTokensSaved,
    },
    'AI triage cost optimization stats',
  )

  // ─── Call AI only for uncached items with CNAE overlap ────────────────────
  if (itemsToCallAI.length > 0) {
    const tenderList = itemsToCallAI
      .map((item: any, i: number) => {
        const valor = item.valorEstimado
          ? `R$ ${item.valorEstimado.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
          : 'N/I'
        const orgao = item.orgao || 'N/I'
        const uf = item.uf || 'N/I'
        return `${i + 1}. ID: ${item.matchId} | Objeto: "${item.objeto}" | Valor: ${valor} | Orgao: ${orgao} | Estado: ${uf}`
      })
      .join('\n')

    const userPrompt = `${companyContext}

---

Analise as seguintes licitacoes e retorne um JSON array com scores de 0-100 para cada uma.

Licitacoes:
${tenderList}

Retorne APENAS um JSON array valido (sem markdown, sem texto adicional):
[{"matchId": "xxx", "score": 85, "recomendacao": "participar|avaliar_melhor|nao_recomendado"}, ...]

LEMBRE: score 0-15 para objetos TOTALMENTE fora do escopo da empresa. Avalie TODAS as ${itemsToCallAI.length} licitacoes.`

    // Use shared LLM client with fallback providers
    const content = await callLLM({
      task: 'onDemandAnalysis', // Uses maxTokens: 8192, temperature: 0.1
      system: TRIAGE_SYSTEM_PROMPT,
      prompt: userPrompt,
      jsonMode: true,
      maxRetries: 2,
    })

    const cleanJson = content.replace(/```json?\s*/gi, '').replace(/```\s*/g, '').trim()

    let parsed: TriageResult[]
    try {
      const raw = JSON.parse(cleanJson)
      parsed = Array.isArray(raw) ? raw : (raw.results || raw.items || raw.data || [])
    } catch {
      logger.error({ content: cleanJson.slice(0, 500), batchSize: itemsToCallAI.length }, 'AI triage batch parse error')
      // Still return results from pre-filter and cache
      if (dbUpdates.length > 0) {
        const settled = await Promise.allSettled(dbUpdates)
        const failedCount = settled.filter((r) => r.status === 'rejected').length
        if (failedCount > 0) {
          logger.warn({ companyId, failedCount, total: dbUpdates.length }, 'Some triage DB updates failed')
        }
      }
      try { await invalidateMatchCaches(companyId) } catch { /* ignore */ }
      return results
    }

    // Build validated results from AI response
    const cacheEntries: Array<{ key: string; result: CachedTriageResult }> = []

    for (const item of parsed) {
      try {
        if (!item.matchId || typeof item.score !== 'number') continue
        let safeScore = Math.min(100, Math.max(0, Math.round(item.score)))
        const match = itemsToCallAI.find((m: any) => m.matchId === item.matchId)
        if (!match) continue

        // Post-AI CNAE validation gate (unchanged)
        const tenderDivisions = match.tenderCnaes.map((c: string) => c.substring(0, 2))
        const hasDirectOverlap = tenderDivisions.some((d: string) => companyDivs.direct.has(d))
        const hasRelatedOverlap = tenderDivisions.some((d: string) => companyDivs.related.has(d))

        if (tenderDivisions.length > 0 && !hasDirectOverlap && !hasRelatedOverlap) {
          // AI gave high score but ZERO CNAE overlap — cap at 35
          safeScore = Math.min(safeScore, 35)
        } else if (tenderDivisions.length > 0 && !hasDirectOverlap && hasRelatedOverlap) {
          // Only related CNAE match — cap at 65
          safeScore = Math.min(safeScore, 65)
        }

        const updatePayload: Record<string, unknown> = {
          score: safeScore,
          match_source: 'ai_triage',
          recomendacao: item.recomendacao || null,
          analyzed_at: now,
        }

        // Save original keyword score if not already saved by a previous AI analysis
        if (match.matchSource !== 'ai' && match.matchSource !== 'ai_triage') {
          updatePayload.keyword_score = match.originalScore
        }

        dbUpdates.push(
          supabase
            .from('matches')
            .update(updatePayload)
            .eq('id', item.matchId),
        )

        results.push({
          matchId: item.matchId,
          score: safeScore,
          recomendacao: item.recomendacao || 'avaliar_melhor',
        })

        // Cache the raw AI result (before CNAE gate) for reuse
        const cKey = cacheKeys.get(item.matchId)
        if (cKey) {
          cacheEntries.push({
            key: cKey,
            result: { score: item.score, recomendacao: item.recomendacao || 'avaliar_melhor' },
          })
        }
      } catch (err) {
        logger.warn({ matchId: item?.matchId, err }, 'Skipping malformed triage item')
      }
    }

    // Cache AI results in batch
    if (cacheEntries.length > 0) {
      await setTriageCachedBatch(cacheEntries)
    }
  }

  // Execute all DB updates in parallel
  if (dbUpdates.length > 0) {
    const settled = await Promise.allSettled(dbUpdates)
    const failedCount = settled.filter((r) => r.status === 'rejected').length
    if (failedCount > 0) {
      logger.warn({ companyId, failedCount, total: dbUpdates.length }, 'Some triage DB updates failed')
    }
  }

  // Invalidate caches
  try {
    await invalidateMatchCaches(companyId)
  } catch (err) {
    logger.error({ companyId, err }, 'Failed to invalidate match caches after AI triage')
  }

  return results
}

// ─── Worker ──────────────────────────────────────────────────────────────────

const BATCH_SIZE = 50 // Items per LLM call (batch classification for efficiency)

const aiTriageWorker = new Worker<AiTriageJobData>(
  'ai-triage',
  async (job) => {
    const { companyId, matchIds } = job.data

    if (!process.env.DEEPSEEK_API_KEY) {
      logger.warn('DEEPSEEK_API_KEY not set — skipping AI triage')
      return
    }

    logger.info({ companyId, matchCount: matchIds.length }, 'Starting background AI triage')

    // Fetch company profile
    const { data: company } = await supabase
      .from('companies')
      .select('*')
      .eq('id', companyId)
      .single()

    if (!company) {
      logger.error({ companyId }, 'Company not found for AI triage')
      return
    }

    // Auto-generate description if missing (one-time, saved to DB)
    const companyData = company as Record<string, unknown>
    if (!companyData.descricao_servicos || String(companyData.descricao_servicos).trim().length < 10) {
      const generated = await autoGenerateDescription(companyData)
      if (generated) {
        companyData.descricao_servicos = generated
      }
    }

    const companyContext = buildCompanyContext(companyData)

    // Build company CNAEs list for CNAE validation gate
    const companyCnaes: string[] = []
    if (companyData.cnae_principal) companyCnaes.push(String(companyData.cnae_principal))
    if (Array.isArray(companyData.cnaes_secundarios)) companyCnaes.push(...(companyData.cnaes_secundarios as string[]))

    // Process in batches of BATCH_SIZE
    let triaged = 0
    let lowScoreCount = 0
    for (let i = 0; i < matchIds.length; i += BATCH_SIZE) {
      const batch = matchIds.slice(i, i + BATCH_SIZE)

      try {
        const results = await triageBatch(batch, companyContext, companyId, companyCnaes)
        triaged += results.length

        for (const r of results) {
          if (r.score < LOW_SCORE_THRESHOLD) lowScoreCount++
        }

        logger.info(
          { companyId, batch: Math.floor(i / BATCH_SIZE) + 1, triaged, total: matchIds.length },
          'AI triage batch complete',
        )
      } catch (err) {
        logger.error({ companyId, err, batch: Math.floor(i / BATCH_SIZE) + 1 }, 'AI triage batch failed')
        // Continue with next batch — don't fail the whole job
      }

      // Small delay between batches to avoid rate limits
      if (i + BATCH_SIZE < matchIds.length) {
        await new Promise((resolve) => setTimeout(resolve, 500))
      }
    }

    logger.info(
      { companyId, triaged, lowScoreCount, total: matchIds.length },
      'Background AI triage complete',
    )

    // Mark company as ready after triage
    await supabase.from('companies').update({ matching_status: 'ready' }).eq('id', companyId).eq('matching_status', 'triaging')

    // Trigger notification check after triage (debounced — fixed jobId prevents queue flooding)
    try {
      const { pendingNotificationsQueue } = await import('../queues/pending-notifications.queue')
      await pendingNotificationsQueue.add(
        `post-triage-notify-${companyId}`,
        {},
        { jobId: `post-triage-notify-${companyId}`, delay: 30_000 },
      )
      logger.info({ companyId }, 'Triggered notification check after triage (30s delay, deduped)')
    } catch {
      // Non-critical — 5-min sweep will catch it
    }

    // Enqueue semantic matching if embedding provider is available and company has embedding
    // Ollama/BGE-M3 always available locally — always check for semantic matching
    {
      try {
        const { data: co } = await supabase
          .from('companies')
          .select('embedding')
          .eq('id', companyId)
          .single()

        if (co?.embedding) {
          const { semanticMatchingQueue } = await import('../queues/semantic-matching.queue')
          await semanticMatchingQueue.add(
            `post-triage-semantic-${companyId}`,
            { companyId },
            { jobId: `post-triage-semantic-${companyId}-${Date.now()}` },
          )
          logger.info({ companyId }, 'Enqueued semantic matching after triage')
        }
      } catch {
        // Non-critical — semantic matching will run in scheduled sweep
      }
    }
  },
  {
    connection,
    concurrency: 2, // 2 companies can be triaged in parallel (reduced from 3 for memory)
    limiter: { max: 10, duration: 60_000 }, // Max 10 jobs per minute
    stalledInterval: 300_000, // 5 min stall timeout
  },
)

aiTriageWorker.on('failed', (job, err) => {
  logger.error({ jobId: job?.id, err }, 'AI triage job failed')
})

export { aiTriageWorker }

// ─── Auto-Generate Company Terms (keywords + capabilities) ──────────────────
//
// Uses DeepSeek to generate a comprehensive list of search terms for a company
// based on its CNAEs, description, and existing keywords. These terms are
// appended to palavras_chave to broaden matching scope.

export async function generateCompanyTerms(companyId: string): Promise<string[]> {
  const { data: company } = await supabase
    .from('companies')
    .select('id, razao_social, cnae_principal, cnaes_secundarios, descricao_servicos, palavras_chave, capacidades')
    .eq('id', companyId)
    .single()

  if (!company) {
    logger.warn({ companyId }, 'Company not found for term generation')
    return []
  }

  const allCnaes: string[] = []
  if (company.cnae_principal) allCnaes.push(String(company.cnae_principal))
  if (Array.isArray(company.cnaes_secundarios)) allCnaes.push(...(company.cnaes_secundarios as string[]))

  if (allCnaes.length === 0 && !company.descricao_servicos) {
    logger.info({ companyId }, 'No CNAEs or description — skipping term generation')
    return []
  }

  const cnaeDescriptions: string[] = []
  for (const cnae of allCnaes) {
    const group = cnae.substring(0, 2)
    if (CNAE_GROUPS[group]) {
      cnaeDescriptions.push(`${cnae}: ${CNAE_GROUPS[group]}`)
    }
  }

  const existingTerms = [
    ...((company.palavras_chave as string[]) || []),
    ...((company.capacidades as string[]) || []),
  ]

  const prompt = `Voce e um especialista em licitacoes publicas brasileiras. Com base no perfil abaixo, gere uma lista ABRANGENTE de termos de busca que esta empresa deveria monitorar em editais de licitacao.

PERFIL DA EMPRESA:
${company.razao_social ? `Razao Social: ${company.razao_social}` : ''}
${cnaeDescriptions.length > 0 ? `CNAEs:\n${cnaeDescriptions.join('\n')}` : ''}
${company.descricao_servicos ? `Descricao: ${String(company.descricao_servicos).slice(0, 800)}` : ''}
${existingTerms.length > 0 ? `Termos atuais: ${existingTerms.join(', ')}` : ''}

INSTRUCOES:
1. Gere 20-40 termos/frases que tipicamente aparecem em OBJETOS de licitacoes que esta empresa poderia participar
2. Inclua variacoes e sinonimos (ex: "software" + "sistema" + "solucao tecnologica" + "plataforma digital")
3. Inclua termos tecnicos do setor (ex: para TI: "infraestrutura de rede", "banco de dados", "cloud computing")
4. Inclua termos de servicos correlatos que a empresa pode oferecer
5. NAO inclua termos genericos como "servico", "fornecimento", "contratacao"
6. NAO inclua termos de setores que a empresa NAO atua
7. Cada termo deve ter 1-4 palavras

Retorne APENAS os termos, um por linha, sem numeracao, sem explicacao.`

  try {
    // Uses LLM cascade — falls back across 7 free providers if any fails
    // (Groq → Qwen3.6 → Nemotron → Llama-3.3 → Hermes → Gemma → GPT-OSS)
    const content = (await callLLM({
      task: 'chat',
      system: 'Voce e um especialista em licitacoes publicas brasileiras que gera termos de busca.',
      prompt,
    })).trim()
    if (!content) return []

    // Parse response: one term per line, clean up
    const newTerms = content
      .split('\n')
      .map(t => t.replace(/^[-•*\d.)\s]+/, '').trim())
      .filter(t => t.length >= 3 && t.length <= 60)
      .filter(t => !t.includes(':') && !t.includes('('))

    if (newTerms.length === 0) return []

    // Merge with existing terms (deduplicate, case-insensitive)
    const existingLower = new Set(existingTerms.map(t => t.toLowerCase().trim()))
    const uniqueNewTerms = newTerms.filter(t => !existingLower.has(t.toLowerCase().trim()))

    if (uniqueNewTerms.length === 0) {
      logger.info({ companyId }, 'All generated terms already exist')
      return []
    }

    // Save merged terms to DB
    const mergedTerms = [...existingTerms, ...uniqueNewTerms]
    // Store new AI-generated terms in palavras_chave
    const mergedKeywords = [
      ...((company.palavras_chave as string[]) || []),
      ...uniqueNewTerms,
    ]

    const { error } = await supabase
      .from('companies')
      .update({ palavras_chave: mergedKeywords })
      .eq('id', companyId)

    if (error) {
      logger.error({ companyId, error }, 'Failed to save generated terms')
      return []
    }

    logger.info(
      { companyId, newTerms: uniqueNewTerms.length, totalKeywords: mergedKeywords.length },
      'Generated and saved company terms',
    )
    return uniqueNewTerms
  } catch (err) {
    logger.warn({ companyId, err }, 'Failed to generate company terms')
    return []
  }
}
